### ISSUE TITLE
Exception: The /workspace/bootstrap/cache directory must be present and writable.

### ISSUE THREAD

**Issue by elijah-schow** [GoogleCloudPlatform/php-docs-samples#1167]
## Related

Split from #852 

## Steps

1. Create a Laravel 6 project based on [this tutorial](https://cloud.google.com/community/tutorials/run-laravel-on-appengine-standard).

2. Create GAE configuration files:

2.a. Create a `.cloudignore` file:
```
# This file specifies files that are *not* uploaded to Google Cloud Platform
# using gcloud. It follows the same syntax as .gitignore, with the addition of
# "#!include" directives (which insert the entries of the given .gitignore-style
# file at that point).
#
# For more information, run:
#   $ gcloud topic gcloudignore
#
.gcloudignore

# If you would like to upload your .git directory, .gitignore file or files
# from your .gitignore file, remove the corresponding line
# below:
.git
.gitignore

# PHP Composer dependencies:
/vendor/

# Ignore .env file for local development
.env
.env.example
```

2.b. Create an `api/app-staging.yaml` file (some variable have been removed for security purposes):
```
service: staging
runtime: php73

runtime_config:
  document_root: public

env_variables:
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp

  APP_DEBUG: true
  LOG_CHANNEL: stack
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: cookie
  SESSION_LIFETIME: 120
```

2.c. Create a `cloudbuild-staging.yaml` file based on [Automate App Engine deployments with Cloud Build](https://cloud.google.com/source-repositories/docs/quickstart-triggering-builds-with-source-repositories):
```
steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app-staging.yaml"]
    timeout: "1600s"
    dir: "api"

  env:
    - COMMIT_SHA=$COMMIT_SHA
```

3. Deploy directly from your local machine.
   ```
   gcloud app deploy app-staging.yaml
   ```
    This should build and deploy successfully, and the deployed website should load.

4. Add a build trigger for the `staging` branch that triggers a build using the `cloudbuild-staging.yaml` configuration.

5. Commit and push your changes the the trigger branch (`staging`).

6. Visit the deployed website.

## Expected

The website loads.

## Actual

```
Exception
The /workspace/bootstrap/cache directory must be present and writable.
```

<img width="1440" alt="Screen Shot 2020-09-08 at 3 37 47 PM" src="https://user-images.githubusercontent.com/17830432/92525339-46757c00-f1e9-11ea-9299-19a9a489e86e.png">

## Environment

macOS Catalina 10.15.6
Laravel Framework 6.18.25
PHP 7.4.7 (local)
PHP 7.3 (Google App Engine Image)

**Comment by bshaffer** [comment]
I believe your issue here is you are using `CACHE_DRIVER: file`. The filesystem on App Engine is not letting you write to `/workspace/bootstrap/cache` because that part of the App Engine filesystem is immuttable.

Try either changing the cache driver to `database` (instructions in that tutorial), or make sure you've modified `bootstrap/app.php ` by adding the following block of code before the return statement. This will allow you to set the storage path to /tmp for caching in production.

```php
# [START] Add the following block to `bootstrap/app.php`
/*
|--------------------------------------------------------------------------
| Set Storage Path
|--------------------------------------------------------------------------
|
| This script allows you to override the default storage location used by
| the  application.  You may set the APP_STORAGE environment variable
| in your .env file,  if not set the default location will be used
|
*/
$app->useStoragePath(env('APP_STORAGE', base_path() . '/storage'));
# [END]
```

The above instructions are in the tutorial mentioned.  If this doesn't work, it's possible the logic has changed for newer versions of Laravel.

**Comment by bshaffer** [comment]
Additionally, @neysi commented this as a fix:

```
gcloud beta app deploy --no-cache
```

Can you try this and see if it works?

**Comment by elijah-schow** [comment]
@bshaffer Hi! Thanks for the help. Unfortunately, I have already tried editing `bootstrap/app.php` in the way you suggested, but it did not fix the issue. Here's my `app.php` file for good measure:

```

**Comment by elijah-schow** [comment]
@bshaffer Hi! Thanks for the help.

1. **App Storage** - Unfortunately, I have already tried editing `bootstrap/app.php` in the way you suggested, but it did not fix the issue. Here's my `app.php` file for good measure:

```
<?php

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| The first thing we will do is create a new Laravel application instance
| which serves as the "glue" for all the components of Laravel, and is
| the IoC container for the system binding all of the various parts.
|
*/
//header('Access-Control-Allow-Origin: *');
//header('Access-Control-Allow-Methods: *');
//header('Access-Control-Allow-Headers: *');

$app = new Illuminate\Foundation\Application(
    $_ENV['APP_BASE_PATH'] ?? dirname(__DIR__)
);

/*
|--------------------------------------------------------------------------
| Bind Important Interfaces
|--------------------------------------------------------------------------
|
| Next, we need to bind some important interfaces into the container so
| we will be able to resolve them when needed. The kernels serve the
| incoming requests to this application from both the web and CLI.
|
*/

$app->singleton(
    Illuminate\Contracts\Http\Kernel::class,
    App\Http\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Console\Kernel::class,
    App\Console\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
);

/*
|--------------------------------------------------------------------------
| Set Storage Path
|--------------------------------------------------------------------------
|
| This script allows you to override the default storage location used by
| the  application.  You may set the APP_STORAGE environment variable
| in your .env file,  if not set the default location will be used
|
*/
$app->useStoragePath(env('APP_STORAGE', base_path() . '/storage'));

/*
|--------------------------------------------------------------------------
| Return The Application
|--------------------------------------------------------------------------
|
| This script returns the application instance. The instance is given to
| the calling script so we can separate the building of the instances
| from the actual running of the application and sending responses.
|
*/

return $app;
```

2. **No Cache** - I already tried using that command in my cloudbuild file with no luck. Here is my `cloudbuild-staging.yaml` file:
```
# [Automate App Engine deployments with Cloud Build](https://cloud.google.com/source-repositories/docs/quickstart-triggering-builds-with-source-repositories)
steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["beta", "app", "deploy", "app-staging.yaml", "--no-cache"]
    timeout: "1600s"
    dir: "api"
# [Structure of a Build Config File](https://cloud.google.com/cloud-build/docs/build-config#structure_of_a_build_config_file)
options:
  env:
    # [Substituting variable values](https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values)
    - COMMIT_SHA=$COMMIT_SHA
```

3. **Cache Driver** - I haven't tried changing the cache driver yet. Given the other changes I made, the file driver _should_ work, but I'll see if changing the driver works.
