### ISSUE TITLE
How to test WordPress Flexible env. locally

### ISSUE THREAD

**Issue by daron4ever** [GoogleCloudPlatform/php-docs-samples#298]
hello everyone!

I would like to test a WordPress application (Flexible Environment) locally with local database, not Cloud SQL.

I have scripted
`$ php -S localhost:8080 wordpress`
It didn't work and got the following errors:
`Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Unknown: Failed opening required 'wordpress' (include_path='.:') in Unknown on line 0`

I think the problem is in my app.yaml.
```
# application: xxxx
# version: 2017-01-10-test
service: default
runtime: php
env: flex

beta_settings:
  cloud_sql_instances: "xxxx:asia-northeast1:xxxxx"

runtime_config:
  document_root: wordpress

env_variables:
  WHITELIST_FUNCTIONS: escapeshellarg,escapeshellcmd,exec,pclose,popen,shell_exec,phpversion,php_uname
```

Please help!
