### ISSUE TITLE
Issue running laravel 5.4 on app engine with second generation cloud sql instance

### ISSUE THREAD

**Issue by iz-ben** [GoogleCloudPlatform/php-docs-samples#371]
I created a laravel application on app engine by following the steps highlighted here https://cloud.google.com/community/tutorials/run-laravel-on-appengine-flexible

I setup everything as indicated and I can even acess the database from my mysql client using all the users I created and make changes to the database, but when I run the application from the app engine url I get this error 

`PDOException in PDOConnection.php line 43: SQLSTATE[HY000] [2002] No such file or directory`

```
 in PDOConnection.php line 43
at PDO->__construct('mysql:unix_socket=/cloudsql/{removed};dbname={removed}', '{removed}', '{removed}', array(0, 2, 0, false, false)) in PDOConnection.php line 43
at PDOConnection->__construct('mysql:unix_socket=/cloudsql{removed};dbname={removed}', {removed}', {removed}', array(0, 2, 0, false, false)) in Connector.php line 65
at Connector->createPdoConnection('mysql:unix_socket=/cloudsql/{removed};dbname={removed}', '{removed}', '{removed}', array(0, 2, 0, false, false)) in Connector.php line 44
at Connector->createConnection('mysql:unix_socket=/cloudsql{removed};dbname={removed}', array('driver' => 'mysql', 'host' => 'localhost', 'port' => '3306', 'database' => {removed}', 'username' => '{removed}', 'password' => {removed}', 'unix_socket' => '/cloudsql/{removed}', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => true, 'engine' => null, 'name' => 'mysql'), array(0, 2, 0, false, false)) in MySqlConnector.php line 24
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'localhost', 'port' => '3306', 'database' => '{removed}', 'username' => '{removed}', 'password' => '{removed}', 'unix_socket' => '/cloudsql/{removed}', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => true, 'engine' => null, 'name' => 'mysql')) in ConnectionFactory.php line 183
```

The thing I don't understand is why I am able to connect to the database using PDO in the standard environment but can't in the flexible and this only affects the laravel installation as provided in the aforementioned tutorial.

Need help because it has been several days without any results

**Comment by bshaffer** [comment]
@iz-ben What does your `app.yaml` look like? Be sure to declare your CloudSQL connection name in `app.yaml` like this: 

```yaml
# Use the connection name obtained when configuring your Cloud SQL instance.
beta_settings:
    cloud_sql_instances: "CONNECTION_NAME"
```

**Comment by McGreeb** [comment]
Did you fix this? I am having the same issue here: https://github.com/GoogleCloudPlatform/php-docs-samples/issues/377

**Comment by bshaffer** [comment]
The issue could be you must use at least version [5.4.16](https://github.com/laravel/laravel/tree/v5.4.16) of Laravel, which has the [appropriate change](https://github.com/laravel/laravel/pull/4179) to support the `DB_SOCKET` environment variable. Check `config/database.php` to ensure the `socket` parameter is there, and if it isn't, add it manually.

**Comment by McGreeb** [comment]
Yeah that fixed it for me, thank you so much. closed my other ticket.

**Comment by iz-ben** [comment]
Sorry @bshaffer. I was away for a while. 
I'm using app.yaml as described in the [file](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/flexible/laravel/app-dbsessions.yaml) in the repository.
I've also tried this [configuration](https://github.com/GoogleCloudPlatform/php-docs-samples/issues/377) updating the relevant connection details but I'm still getting the error

```
SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from `sessions` where `id` = SS8nl94ojIxI5uaHMbA5nRSPnJssxoFeOom2C5ZM limit 1)
```
I'm stumped because the SQL instance lives in the same project as the app engine

**Comment by bshaffer** [comment]
@iz-ben this is indeed very strange. One way you can debug this is see if the socket exists on the machine. SSH into one of your production app engine instance and do an `ls -la /cloudsql` and you should see a file there matching the values in `app.yaml`. Additionally, you can verify the socket exists in the container itself by running `sudo docker exec -it gaeapp /bin/bash` and run the same `ls` command.

**Comment by bshaffer** [comment]
closing due to inactivity

**Comment by juceberipe** [comment]
I have the same problem.

**Comment by bshaffer** [comment]
For anyone showing up here, somebody claims the issue was solved by removing the quotes from the cloud instance in beta settings. So from `cloud_sql_instances: "YOUR_CLOUDSQL_CONNECTION_NAME"` to `cloud_sql_instances: 
YOUR_CLOUDSQL_CONNECTION_NAME`

**Comment by dimakrol** [comment]
Have same issue. Laravel 5.5.19 version.

My config:

```yaml
runtime: php
env: flex

runtime_config:
  document_root: public

skip_files: 
    -.env

beta_settings:
  cloud_sql_instances: ttt-180713:europe-west1:ttt-mysql

env_variables:
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:oqUyw6PCgTeACFhautIOEx8Uia958GBodb4p+9KouVk=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: ttt
  DB_USERNAME: ttt
  DB_PASSWORD: ''
  DB_SOCKET: "/cloudsql/ttt-180713:europe-west1:ttt-mysql"
```
Can anybody help or give advice how I can debug or fix it?
