### ISSUE TITLE
Unable to connect to Cloud SQL

### ISSUE THREAD

**Issue by McGreeb** [GoogleCloudPlatform/php-docs-samples#377]
I am unable to conect to cloud SQL from laravel in app engine. If I use the cloud sql proxy I am able to connect to the google SQL from my local version of laravel but not form within app engine.

Here is my app.yaml:

```
env: flex
runtime:        php
api_version:    1

runtime_config:
  document_root: public
  
beta_settings:
    cloud_sql_instances: "single-quanta-158320:us-east1:officesweeet-test"
    
handlers:
        - url: /favicon\.ico
          static_files: public/favicon.ico
          upload: public/favicon\.ico

        - url: /build
          static_dir: public/build
          application_readable: true

        - url: /images
          static_dir: public/images

        - url: /includes
          static_dir: public/includes

        - url: /phpmyadmin
          static_dir: public/phpmyadmin

        - url: /.*
          script: public/index.php

skip_files:
        - ^(.*/)?#.*#$
        - ^(.*/)?.*~$
        - ^(.*/)?.*\.py[co]$
        - ^(.*/)?.*/RCS/.*$
        - ^(.*/)?\.(?!env).*$
        - ^(.*/)?node_modules.*$
        - ^(.*/)?_ide_helper\.php$
        - ^(.*/)?\.DS_Store$

env_variables:
  APP_LOG: errorlog
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_DATABASE: database
  DB_USERNAME: username
  DB_PASSWORD: password
  DB_SOCKET: /cloudsql/single-quanta-158320:us-east1:officesweeet-test
        

```
One thing I have noticed is if I look at the config in the app engine panel i get the following

```
runtime: php
env: flexible
threadsafe: true
handlers:
  - url: "/favicon\\.ico"
    application_readable: false
    static_files: public/favicon.ico
    require_matching_file: false
    upload: "public/favicon\\.ico"
  - url: '/build/(.*)'
    application_readable: true
    static_files: "__static__/public/build/\\1"
    require_matching_file: false
    upload: '__static__/public/build/.*'
  - url: '/images/(.*)'
    application_readable: false
    static_files: "public/images/\\1"
    require_matching_file: false
    upload: 'public/images/.*'
  - url: '/includes/(.*)'
    application_readable: false
    static_files: "public/includes/\\1"
    require_matching_file: false
    upload: 'public/includes/.*'
  - url: '/phpmyadmin/(.*)'
    application_readable: false
    static_files: "public/phpmyadmin/\\1"
    require_matching_file: false
    upload: 'public/phpmyadmin/.*'
  - url: '/.*'
    script: public/index.php
env_variables:
  APP_LOG: errorlog
  CACHE_DRIVER: database
  DB_CONNECTION: mysql
  DB_DATABASE: officesweeet
  DB_HOST: localhost
  DB_PASSWORD: password
  DB_SOCKET: '/cloudsql/single-quanta-158320:us-east1:officesweeet-test'
  DB_USERNAME: username
  SESSION_DRIVER: database
  STORAGE_DIR: /tmp
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
```
I have noticed the beta settings are missing from this. Could this be a problem?
