### ISSUE TITLE
There is no place here for the project.

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/php-docs-samples#474]
In php-docs-samples/appengine/standard/cloudsql/app.yaml we see

```
# [START env]
env_variables:
  # Replace project, instance, database, user and password with the values obtained
  # when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/INSTANCE_CONNECTION_NAME;dbname=DATABASE
  MYSQL_USER: root
  MYSQL_PASSWORD: ''
# [END env]
```

"Replace project, instance, database, user and password with the values obtained"

There is no place here for the project.
