### ISSUE TITLE
[Symfony] Monolog FingersCrossed handler doesn't send passthru_level logs to Stackdriver

### ISSUE THREAD

**Issue by gmdev** [GoogleCloudPlatform/php-docs-samples#847]
My Monolog configuration is as follows:

```
monolog:
    handlers:
        fingers_crossed:
            type: fingers_crossed
            action_level: error
            passthru_level: notice
            handler: nested_stackdriver
            excluded_http_codes: [404]
        nested_stackdriver:
            type: service
            id: monolog_psr_batch_logger

services:
    monolog_psr_batch_logger:
        class: Monolog\Handler\PsrHandler
        arguments: ['@google_cloud_stackdriver_psr_batch_logger']

    # PsrBatchLogger
    google_cloud_stackdriver_psr_batch_logger:
        class: Google\Cloud\Logging\PsrLogger
        factory: ['Google\Cloud\Logging\LoggingClient', 'psrBatchLogger']
        arguments: ['app']
```

It works fine for logs triggering the `action_level` (e.g. on exception all logs are properly sent to Stackdriver - including `debug` logs).

However for logs which only trigger the `passthru_level` (`notice` in the example above) the logs are not visible in the Logs Viewer in GCP.

See screen:

![stackdriver](https://user-images.githubusercontent.com/1126031/53561654-c11eff00-3b4f-11e9-9af6-bcd970a7d3ee.png)

(I went through the setup instructions: https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/php72/symfony-framework)
