### ISSUE TITLE
laravel 5.8 install in App Engine Standard

### ISSUE THREAD

**Issue by carlospalacin** [GoogleCloudPlatform/php-docs-samples#855]
I tried to install with Laravel 5.8 clean installation and get the following error:
```
ErrorException
file_put_contents(/tmp/framework/sessions/sVxzLycN8fOEMA8szh1cwRnIOsMmuAx6ClFlDUAx
```

The same installation works fine with laravel 5.7 works fine, any recommendation?

Thanks!

**Comment by bshaffer** [comment]
Yes, if you add `SESSION_DRIVER: cookie` to your `app.yaml` environment variables, this issue will be fixed.  See https://github.com/GoogleCloudPlatform/php-docs-samples/pull/856:

```yaml
# app.yaml
runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: YOUR_APP_KEY
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
```
